// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE-RNzqwOaWDF2jiWMzEq9VIQNO8TR5jk',
    appId: '1:516207321515:web:7ffd351fca9414331cf2ee',
    messagingSenderId: '516207321515',
    projectId: 'ranking-6f772',
    authDomain: 'ranking-6f772.firebaseapp.com',
    storageBucket: 'ranking-6f772.appspot.com',
    measurementId: 'G-R8JRPS3158',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwDmfGKv-A4zKdRjzpJhUFPtfYhl77khQ',
    appId: '1:516207321515:android:3c9d9365e8688a091cf2ee',
    messagingSenderId: '516207321515',
    projectId: 'ranking-6f772',
    storageBucket: 'ranking-6f772.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqOlSBbnABFVqBU-IcfCPxwT6hxwVO80Y',
    appId: '1:516207321515:ios:d3a9994ca9f414251cf2ee',
    messagingSenderId: '516207321515',
    projectId: 'ranking-6f772',
    storageBucket: 'ranking-6f772.appspot.com',
    iosBundleId: 'com.example.dyplom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqOlSBbnABFVqBU-IcfCPxwT6hxwVO80Y',
    appId: '1:516207321515:ios:d3a9994ca9f414251cf2ee',
    messagingSenderId: '516207321515',
    projectId: 'ranking-6f772',
    storageBucket: 'ranking-6f772.appspot.com',
    iosBundleId: 'com.example.dyplom',
  );
}
